name: Build and deploy on push

on: 
  push:
    branches:
     - source
  pull_request:


jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/source'
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - run: echo "Running entrypoint.sh"
    - run: ./entrypoint.sh
      env:
        BUILD_ONLY: true
        PAGES_BRANCH: master

  publish:
    name: Publish site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/source'
    permissions:
      contents: write
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.12.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PAGES_BRANCH: master
